name: publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - run: bun install

      - name: Publish
        run: bun run scripts/publish.ts --version=${VERSION#v}
        env:
          VERSION: ${{ github.ref_name }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
